-- battle_simulator.pokemon definition

CREATE TABLE `pokemon` (
  `name` varchar(100) NOT NULL,
  `abilities` text,
  `against_bug` float DEFAULT NULL,
  `against_dark` float DEFAULT NULL,
  `against_dragon` float DEFAULT NULL,
  `against_electric` float DEFAULT NULL,
  `against_fairy` float DEFAULT NULL,
  `against_fight` float DEFAULT NULL,
  `against_fire` float DEFAULT NULL,
  `against_flying` float DEFAULT NULL,
  `against_ghost` float DEFAULT NULL,
  `against_grass` float DEFAULT NULL,
  `against_ground` float DEFAULT NULL,
  `against_ice` float DEFAULT NULL,
  `against_normal` float DEFAULT NULL,
  `against_poison` float DEFAULT NULL,
  `against_psychic` float DEFAULT NULL,
  `against_rock` float DEFAULT NULL,
  `against_steel` float DEFAULT NULL,
  `against_water` float DEFAULT NULL,
  `attack` int DEFAULT NULL,
  `base_egg_steps` int DEFAULT NULL,
  `base_happiness` int DEFAULT NULL,
  `base_total` int DEFAULT NULL,
  `capture_rate` int DEFAULT NULL,
  `classfication` text,
  `defense` int DEFAULT NULL,
  `experience_growth` int DEFAULT NULL,
  `height_m` float DEFAULT NULL,
  `hp` int DEFAULT NULL,
  `japanese_name` varchar(100) DEFAULT NULL,
  `percentage_male` float DEFAULT NULL,
  `pokedex_number` int DEFAULT NULL,
  `sp_attack` int DEFAULT NULL,
  `sp_defense` int DEFAULT NULL,
  `speed` int DEFAULT NULL,
  `type1` varchar(50) DEFAULT NULL,
  `type2` varchar(50) DEFAULT NULL,
  `weight_kg` float DEFAULT NULL,
  `generation` int DEFAULT NULL,
  `is_legendary` int DEFAULT NULL,
  PRIMARY KEY (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;